### ISSUE TITLE
java.lang.NoSuchMethodError: com.codeborne.selenide.SelenideWait.withTimeout

### ISSUE THREAD

**Issue by Salamander75** [selenide/selenide#877]
## The problem
We have updated our Selenide version to 5.0.1 and my test uses _confirm_("Some text") method. It used to work in Selenide 4.2. But now I get error: java.lang.NoSuchMethodError: com.codeborne.selenide.SelenideWait.withTimeout

## Details
We use Java 8 JDK
We use the following dependencies for UI testing:
        dependency 'org.seleniumhq.selenium:selenium-server-standalone:2.46.0'
        dependency 'org.seleniumhq.selenium:selenium-remote-driver:3.141.59'
        dependency 'org.seleniumhq.selenium:selenium-api:3.141.59'
        dependency 'org.seleniumhq.selenium:selenium-java:3.141.59'
        dependency 'com.codeborne:selenide:5.0.1'
And compilation:
    testCompile 'org.seleniumhq.selenium:selenium-api'
    testCompile 'org.seleniumhq.selenium:selenium-remote-driver'
    testCompile 'org.seleniumhq.selenium:selenium-server-standalone'
    testCompile 'org.seleniumhq.selenium:selenium-java'
    testCompile 'com.codeborne:selenide'

The error comes in SelenideWait.java class. There are two methos:
_    withTimeout(Duration.of(timeout, ChronoUnit.MILLIS));
    pollingEvery(Duration.of(pollingInterval, ChronoUnit.MILLIS));_

Both of them have red line under them

**Comment by BorisOsipov** [comment]
@Salamander75 can you remove all selenium dependencies from your build file and confirm that issue reproduces?

**Comment by BorisOsipov** [comment]
at least remove `selenium-server-standalone`

**Comment by Salamander75** [comment]
Yes the error is still there. I removed standalone server dependency. Could not remove the others though, otherwise other errors occured

**Comment by BorisOsipov** [comment]
@Salamander75 
>Could not remove the others though, otherwise other errors occured

Which one? In fact you need only selenide deps to work with selenium.

**Comment by Salamander75** [comment]
Well if I only left dependency 'com.codeborne:selenide:5.0.1' and tried to run my test, then for example the following errors occured:

Error:(220, 27) java: cannot access org.openqa.selenium.WrapsDriver
  class file for org.openqa.selenium.WrapsDriver not found

Error:(54, 38) java: cannot access org.openqa.selenium.interactions.internal.Locatable
  class file for org.openqa.selenium.interactions.internal.Locatable not found

**Comment by Salamander75** [comment]
And I would like to add that those errors which I mention above about SelenideWait.java class also still persist

**Comment by Salamander75** [comment]
Hello. Sorry for delay. Was off from work and also had to get a permission to share.
Gist file for build.gradle https://gist.github.com/Salamander75/9e20e04a70e7101ece844c0896e926bd

**Comment by asolntsev** [comment]
@Salamander75 Clearly, you have too old `selenium-support-*.jar`. 
Please execute `./gradlew dependenices` and see which version of `selenium-support` are you getting and why.

**Comment by Salamander75** [comment]
Okay. My progress has been the following: Since I am using Spring Boot version 1.5.13.RELEASE and according to https://docs.spring.io/spring-boot/docs/2.1.1.RELEASE/reference/htmlsingle/#appendix-dependency-versions, it downloads Selenium versions 2.53.1 and it overrides the versions what Selenide tries to bring to application (in short, Selenide tries to use versions 3.*.* of Selenium but Boot overrides them with 2.53.1. And at the moment we cannot upgrade Boot to version 2 (it has to be 1.5.13 RELEASE). By upgrading also selenium-support to the latest  version seemed to fix my errors ( for now :D ). 
Thank you for your help.

**Comment by BorisOsipov** [comment]
@Salamander75 Ok. Happy coding!
