### ISSUE TITLE
NoClassDefFoundError: org/apache/hc/core5/http/ClassicHttpRequest error being thrown on Selenide 6.12.0+

### ISSUE THREAD

**Issue by cemerick1** [selenide/selenide#2199]
## NoClassDefFoundError: org/apache/hc/core5/http/ClassicHttpRequest error being thrown on Selenide 6.12.0+
When updating the build.gradle from 6.11.1 to 6.12.0 or the latest 6.12 release I get the error above.

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* selenide 6.12.2 
* Edge v110.0.1587.69

![image](https://user-images.githubusercontent.com/43388329/224352004-557995b3-b908-4d3c-8e25-efc0e3ed9799.png)

**Comment by asolntsev** [comment]
@cemerick1 Apparently, there is a conflict in your dependencies. Just run `mvn dependency:tree` or `gradle dependencies`, and you will see that version of Apache http client you are using. 

See https://selenide.org/2020/11/17/why-proxy-does-not-work-in-selenoid/ for more details.
