### ISSUE TITLE
Selenide tests failed after upgrading to 6.17.2 from 5.12.2 which throws NoSuchMethodError

### ISSUE THREAD

**Issue by LidiyaBabu** [selenide/selenide#2450]
My existing tests failed when Selenide was upgraded to 6.17.2 from 5.12.2

I have a sample Selenide project which is working fine with  Selenide 5.12.2
I just wanted to upgrade to the latest version and try new features

```java
It throws java.lang.NoSuchMethodError: 'org.openqa.selenium.WebDriver$Timeouts org.openqa.selenium.WebDriver$Timeouts.pageLoadTimeout(java.time.Duration)' after the browser gets launched
```

* Selenide Version: 6.17.2
* Chrome: 116
* Browser Driver Version: 116
* Selenium Version: 4.11

**Comment by asolntsev** [comment]
@LidiyaBabu I think you have incorrect versions of dependencies. Just run `gradlew dependencies` or `mvn dependency:tree` and check which versions of `selenium-*.jar` you have. 

See https://selenide.org/2020/11/17/why-proxy-does-not-work-in-selenoid/ and https://www.javaadvent.com/2020/12/how-to-debug-dependency-conflicts-in-maven-and-gradle.html
