### ISSUE TITLE
Updating to 6.18.0 throws numerous lodash errors in our application

### ISSUE THREAD

**Issue by cemerick1** [selenide/selenide#2471]
## The problem
Since updating selenide to 6.18.0 in our build.gradle file, the driver appears to be throwing numerous issues with what appear to be [lodash ](https://lodash.com/docs/4.17.15) functions.  When downgrading to 6.17.2 I do not get these issues and tests are run free of error.  Clicking buttons on 6.18.0 also appears to be flaky in that no action proceeds from clicking etc..

## Details
![image](https://github.com/selenide/selenide/assets/43388329/5ae12f34-0ee5-4c18-a49a-c1f78c8bbb7e)

I have also submitted a ticket to our developers to see if its a problem on our end as well.  Below you will find the console logs. Any help in remedying this is greatly appreciated! Also apologies for the long log output but I am trying to provide as much info as possible.

## Browser Console Logs
Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1 TypeError: [Company Error] _.filter is not a function
    at i.remove (https://preview-staging.companyonline.net/n/Bundles/Layout/Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1:73302)
    at r (https://preview-staging.companyonline.net/n/Bundles/Layout/Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1:70803)
    at l (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:50352)
    at l (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:50352)
    at https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:51029
    at a.$eval (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:56117)
    at a.$digest (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:54622)
    at a.$apply (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:56436)
    at k (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:36460)
    at it (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:38548) undefined
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
(anonymous) @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
l @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
l @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$eval @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$digest @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$apply @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
it @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k.onreadystatechange @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1 Error: [Company Error] _.filter is not a function Object
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
i @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
(anonymous) @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
l @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
l @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$eval @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$digest @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$apply @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
it @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k.onreadystatechange @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1 TypeError: [Company Error] _.uniq is not a function
    at a.<anonymous> (https://preview-staging.companyonline.net/n/Bundles/Layout/Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1:83605)
    at i (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:89526)
    at | (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:83120)
    at l.constant (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:88898)
    at Object.p (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:53757)
    at a.$digest (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:54737)
    at a.$apply (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:56436)
    at k (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:36460)
    at it (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:38548)
    at k.onreadystatechange (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:39091) undefined
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
(anonymous) @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
$digest @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$apply @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
it @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k.onreadystatechange @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1 Error: [Company Error] _.uniq is not a function Object
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
i @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
(anonymous) @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
$digest @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$apply @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
it @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k.onreadystatechange @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1 TypeError: [Company Error] _.each is not a function
    at a.<anonymous> (https://preview-staging.companyonline.net/n/Bundles/Layout/Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1:83795)
    at i (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:89526)
    at | (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:83120)
    at l.constant (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:88898)
    at Object.p (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:53757)
    at a.$digest (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:54737)
    at a.$apply (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:56436)
    at k (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:36460)
    at it (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:38548)
    at k.onreadystatechange (https://preview-staging.companyonline.net/n/Bundles/Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1:39091) undefined
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
(anonymous) @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
$digest @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$apply @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
it @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k.onreadystatechange @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1 Error: [Company Error] _.each is not a function Object
(anonymous) @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
i @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
(anonymous) @ Header?v=XAeYNenMXl3k_RRpVobw7CdoRyt1PTsAHtllw8m5iO01:1
$digest @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
$apply @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
it @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1
k.onreadystatechange @ Angular1.2.x?v=tMUghTvZuIxsd6c9jgyfuXiER5jkDjDJ5b7F3BfUJcU1:1

## Tell us about your environment
* **Selenide**: 6.18.0 
* **Gauge**: 0.10.2
* **Chrome**: 116.0.5845
* **Firefox**: 117.0.1
* **Windows 10 Version**: 10.0.19045 Build 19045

**Comment by BorisOsipov** [comment]
Hi @cemerick1! 
It is a selenium bug https://github.com/SeleniumHQ/selenium/issues/12659
Nothing to fix from our side.

**Comment by cemerick1** [comment]
Thanks @BorisOsipov I really appreciate it!
